# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  steps:
  - task: UseDotNet@2 
  inputs: version: '3.0.x'
  - task: UseDotNet@2 
  inputs: version: '2.2.x' 
  packageType: runtime
steps:
 - task: DotNetCoreCLI@2 
 inputs: command: restore 
 projects: '**/*.csproj' 
 feedsToUse: config 
 nugetConfigPath: NuGet.config # Relative à votre repertoire 
externalFeedCredentials: <Name of the NuGet service connection>
steps: 
- task: DotNetCoreCLI@2 
displayName: 
Build inputs: 
command: build 
projects: '**/*.csproj' 
arguments: '--configuration Release' # modifier selon vos besoins
